### ISSUE TITLE
Any Chinese based demo?

### ISSUE THREAD

**Issue by lucasjinreal** [Ber666/llm-reasoners#20]
Hello, new to llm reasoner, wanna ask is there any speicifc problem solving examples in Chinese? Such as let llm do a real world task with reasoning? Like querying LK99 news based on it's web tools? Or calculating with 100% correctness on some complicated math problems?

**Comment by Ber666** [comment]
Hi, thanks for your interest in this project! Unfortunately, we don't have examples of solving real-world problems in Chinese for now.

1. Though we only include several standard benchmarks in this project currently, solving real-world problems is definitely a possible and more way interesting application of LLM Reasoners. We have ongoing research projects toward this goal and will update the examples once we get some results.

2. It'll be very interesting to see Chinese examples running with LLM Reasoners. However, we already have a long to-do list and may not be able to prioritize this task. PRs are welcome and appreciated if anyone wants to contribute!
