### ISSUE TITLE
visualizer fails for gsm8k

### ISSUE THREAD

**Issue by chris-aeviator** [Ber666/llm-reasoners#26]
when trying to load a gsm8k run with the visualizer, the code fails
```
    import pickle
    from reasoners.visualization import visualize
    with open("logs/gsm8k/myfolder/1.pkl", 'rb') as f:
        mcts_result = pickle.load(f)
    visualize(mcts_result)
```

  
```
  llm-reasoners/reasoners/visualization/tree_log.py:52, in TreeLog.from_mcts_results.<locals>.default_node_data_factory(n)
       51 def default_node_data_factory(n: MCTSNode) -> NodeData:
  ---> 52     return NodeData(n.state._asdict() if n.state else {})
  
  AttributeError: 'list' object has no attribute '_asdict'
```

#### EDIT:
the json file works fine with the online visualizer upload 

#### EDIT 2:
where can I find the code for the visualizer, I see the code here connecting to the llm-reasoners.net front & backend which is really not ideal as a dependency.

**Comment by Ber666** [comment]
Hi, could you try following the jupyter notebook to visualize GSM8k? The state defined in gsm8k example is a list, which is not supported in default_node_factory. We will make sure they are compatible in the future.

**Comment by chris-aeviator** [comment]
thanks - I never saw this file! Feel free to keep open or close this issue as is most convenient to you for PM.

**Comment by Ber666** [comment]
Fixed
