### ISSUE TITLE
Including GRACE decoding 

### ISSUE THREAD

**Issue by mukhal** [Ber666/llm-reasoners#27]
Thanks for the amazing repo. I am the first author of [GRACE Decoding](https://github.com/mukhal/grace/tree/main) and I think LLM-reasoners could benefit from having GRACE included. I would be happy to help with this, so let me know!

**Comment by Ber666** [comment]
Thanks for your suggestion! As discussed in our meeting, we will work on it as soon as the trained checkpoints are available.

**Comment by chris-aeviator** [comment]
@Ber666 what's the timeline for the release of the model (if I may hijack this issue for raising the question) ?

**Comment by mukhal** [comment]
@chris-aeviator sorry for the late response. The model is now released!

**Comment by chris-aeviator** [comment]
@mukhal very exciting!

@Ber666 mind reopening this issue now that the model is avail?

**Comment by Ber666** [comment]
Our team is working on it. Stay tuned!
