### ISSUE TITLE
World model `step` return type mismatch in MCTS implementation

### ISSUE THREAD

**Issue by xiyan128** [Ber666/llm-reasoners#40]
World models' `step` function is supposed to return the world model's state.
https://github.com/Ber666/llm-reasoners/blob/504afc75e158faeabcda1b92215b691dee941627/reasoners/base.py#L88

However, in the MCTS implementation, it is expected to also return `aux`.
https://github.com/Ber666/llm-reasoners/blob/52ef9901d35f3074576345f17d4b3e8fe9c600f4/reasoners/algorithm/mcts.py#L168

Should we update base class' `step` function signature to match the usages?

**Comment by andreasbinder** [comment]
I would say that makes sense :)
