### ISSUE TITLE
Download val error in Blocksworld

### ISSUE THREAD

**Issue by lzwqjh** [Ber666/llm-reasoners#44]
We follow the readme file in the examples folder. In Blocksworld, we download the val files via the link provided, but the link page say: **This page does not exist yet.** 
Screenshot below：
![image](https://github.com/Ber666/llm-reasoners/assets/48863392/d95d0552-50a0-463e-a871-8fb10d17b12e)

Could you tell us how to solve this problem. we will be very grateful. Thanks.

**Comment by Ber666** [comment]
Hi, this seems to be due to an update of FastDownward website.. Could you try following the alternative mentioned [here](https://github.com/karthikv792/LLMs-Planning/tree/main/llm_planning_analysis)?
