### ISSUE TITLE
Blocksworld Example Runtime Error: 'NoneType' object has no attribute 'cadam32bit_grad_fp32'

### ISSUE THREAD

**Issue by QubitPi** [Ber666/llm-reasoners#45]
Dear llm-reasoners team, we have [setup reasoners](https://github.com/Ber666/llm-reasoners#installation) in a Mac machine and are following the [Blocksworld](https://github.com/Ber666/llm-reasoners/tree/main/examples#blocksworld) example in order to try out how reasoner works. Executing [this command](https://github.com/Ber666/llm-reasoners/tree/main/examples#:~:text=CUDA_VISIBLE_DEVICES%3D0%2C1%2C2%2C3%20python%20%2Dm%20torch.distributed.run%20%2D%2Dnproc_per_node%204%20examples/rap_blocksworld/inference.py%20%2D%2Dllama_size%20%2230B%22%20%2D%2Ddata_path%20%27examples/rap_blocksworld/data/step_4.json%27%20%2D%2Ddepth_limit%204%20%2D%2Doutput_trace_in_each_iter) (`CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.run --nproc_per_node 4 examples/rap_blocksworld/inference.py --llama_size "30B" --data_path 'examples/rap_blocksworld/data/step_4.json' --depth_limit 4 --output_trace_in_each_iter
`) results in the following error:

```
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
```

Could we get some hints on how to resolve this?

Thank you for your attention.

**Comment by Ber666** [comment]
Hi, the code is mainly for NVIDIA GPUs. If you want to run experiments on Mac, you may want to set up [llama.cpp](https://github.com/ggerganov/llama.cpp) and use our library with llama.cpp interface. We haven't tested it on mac, but it should easy to make it work.
