### ISSUE TITLE
fast_reward() for GSM8K always returns 0 

### ISSUE THREAD

**Issue by mukhal** [Ber666/llm-reasoners#48]
Why does fast_reward return 0 [here](https://github.com/Ber666/llm-reasoners/blob/1d6b03a490ff02a3d48fd080b220c4c1e1d3baf5/examples/rap_gsm8k/search_config.py#L107C1-L108C1)? 

Is this a bug?

**Comment by wu-qing-157** [comment]
I'm sorry there seems to be some version control issues. This should be fixed in #49.
